language: c++
compiler: gcc
sudo: false
matrix:
  include:
  - os: osx
    env:
    - TARGET="docs"
  exclude:
  - compiler: gcc
install:
- if [ "$TARGET" == "android" ] || [ "$TARGET" == "linux" ] || [ "$TARGET" == "docs" ]; then
    scripts/ci/$TARGET/install.sh;
  fi
script:
- scripts/ci/$TARGET/build.sh $OPT
- if [ "$TARGET" == "osx" ] || [ "$TARGET" == "linux" ]; then
    scripts/ci/$TARGET/run_tests.sh;
  fi
after_success:
- if [ "$TARGET" == "docs" ]; then
    scripts/ci/$TARGET/after_success.sh;
  fi
git:
  depth: 1
env:
  global:
  - secure: dyeJqawQIXyF8enoShkp5mwk7FPH6MEM0YsniX0bxUGj1yJ/hNfAXbrz9mmfiRuO0creHKMFr+5yN+M791yxZ1p3i/0MQ0AS8YnAwdwd4stqg2qr5Ftbuw5bUPZ4mU+9giPHwLELT01qiDURblCJY01jC1ybXY8vmuwX9QEuhic=
